global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:5000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cAdvisor:8080"]

  - job_name: "mysqld"
    static_configs:
      - targets: ["mysqld-exporter:9104"]
